version: "{branch}-{build}"
environment:
 PY_PYTHON: 3.7-32
install:
  - py -m pip install markdown scons

build_script:
  - c:\python37\scripts\scons
  - c:\python37\scripts\scons pot

artifacts:
  - path: '*.nvda-addon'
    name: addon
    type: application/x-nvda-addon
  - path: '*.pot'
    type: application/x-pot
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: addon
  draft: false
  prerelease: false
  auth_token:
    secure: T5Xj+3ra81bk/wX0MFN3ADsbpOQ0gDOeQZFENqV3VV+lujPeeZUGmbCzhTPUGYXW
  on:
    appveyor_repo_tag: true        # deploy on tag push only