[tool.ruff]
builtins = [
    "_",
    "pgettext",
]
exclude = [
    ".git",
    "__pycache__",
]
ignore = [
	"W191"
]
line-length = 110
select = [
    "C9",
    "E",
    "F",
    "W",
]

[tool.ruff.mccabe]
max-complexity = 15

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
