builtins = [
	"_",  # translation lookup
	"ngettext",  # translation lookup
	"pgettext",  # translation lookup
	"npgettext",  # translation lookup
]
exclude = [  # don't bother looking in the following subdirectories / files.
	".git",
	"__pycache__",
]
line-length = 110
output-format = "full"
src = ["addon"]
target-version = "py37"

[lint]
ignore = [
	"W191",  # indentation contains tabs
]
logger-objects = ["logHandler.log"]
select = [
	"A",  # flake8-builtins
	"ARG",  # flake8-unused-arguments 
	"B",  # flake8-bugbear
	"C90", # mccabe
	"E",  # pycodestyle Error
	"F",  # Pyflakes
	"FIX",  # flake8-fixme
	"I",  # isort
	"INT",  # flake8-gettext 
	"UP",  # pyupgrade
	"W",  # pycodestyle Warning
]
mccabe.max-complexity = 15

[format]
line-ending = "auto"
quote-style = "double"
indent-style = "tab"
